ERD
Chanmi-Gim/Express pull request #2
Opened 2023-08-07 10:23 UTC by Chanmi-Gim

# **온라인청첩장 ERD**
<img width="440" alt="스크린샷 2023-08-07 오후 6 56 22" src="https://github.com/Chanmi-Gim/Express/assets/117872640/e13d36f0-96d8-43ed-be2b-03b4cb457e58">

Hey Soo could you look at my ERD?!

2023-08-07 10:37 UTC, kakasoo commented
1
PK 커플 아이디가 카멜 케이스인데 스네이크로 마저 수정해주세요. 수정해야 하는 이유는 카톡으로 말씀드렸다시피 DB가 대소문자 구분을 안하는 게 표준이기 때문입니다.

2
draw.io로 ERD를 그린 거면 Repository를 지정할 수 있습니다. ERD도 커밋 내역에 포함해서 변화를 추적할 수 있게 해주세요.

3
청첩장 서비스는 회원가입, 로그인이 조금 특이할 거 같긴 합니다만, "유저"로 정의된 사람들은 어디에 저장할 건지 말씀해주세요. 이 구조에서는 신랑과 신부일 겁니다. 그러면 회원가입과 로그인은 어떻게 될까요?
굳이 이 둘을 구분지어서 테이블을 나누기 보다는 신랑과 신부를 의미하는 tiny int 칼럼을 만드는 게 나아 보입니다.

5
이 테이블에는 초대 테이블이 없습니다. 참석자 테이블이 초대 받은 사람들을 의미하고, 실제 참석 여부를 bool 칼럼으로 관리할 계획인 거라면 테이블 이름을 고쳐주세요.

6
FK에 대해서 완전히 잘못 이해하고 있습니다. 서로가 서로의 FK를 가지는 구조가 가능한가요? 결혼 일정 관리 테이블에 참석자 id가 있다면 참석자가 10명이면 결혼 일정 관리 row도 10개 생성할 건가요?
FK와 정규화에 대해 알아보세요 :)

2023-08-07 10:38 UTC, kakasoo commented
7
커플 일정 관리 테이블과 신랑, 신부가 일대 다 관계인 게 가능할까요?
커플 일정 하나 당 여러 명의 신랑, 여러 명의 신부가 존재할까요?
마찬가지로 잘못된 ERD 설계입니다.
뭐가 1이고 뭐가 다수인지 잘 생각해보세요.

2023-08-07 10:39 UTC, kakasoo requested changes

2023-08-07 10:39 UTC, kakasoo commented on index.html
> +        <p>express~~~ new2</p>
코드리뷰 요청을 위해 아무거나 수정하셨군요~
고생하셨습니다.
오늘은 PR 요청과 첫 ERD 그림으로도 진짜 큰 도전이셨어요. ( 갈 길은 매우 멉니다 )

2023-08-07 12:05 UTC, Chanmi-Gim commented
<img width="549" alt="스크린샷 2023-08-07 오후 8 59 44" src="https://github.com/Chanmi-Gim/Express/assets/117872640/d5499b43-7e15-44ef-a29a-0ac0644eb1b8">

1. PK couple_id 스네이크 표기법으로 수정했습니다.

2. VScode 확장프로그램인 draw.io로 그린 ERD 결과를 커밋/푸시를 하려고 하니 자꾸 아래의 에러가 뜨는데 
hint: Updates were rejected because the remote contains work that you do 
진행중인 이 PR이 아직 종료가 되지 않아 그러는 것 같아 이번 코멘트에서는 캡쳐한 사진으로 공유합니다. 

3. 일반 유저들은 로그인하지 않고 관리자가 만든 페이지링크를 공유하도록 만들 예정입니다. 즉, 관리자만 로그인이 가능하고 청첩장 관련 수정 사항을 반영할 수 있도록 admin_id, admin_password, couple_id를 속성으로 갖는 관리자 로그인테이블을 새로 생성했습니다.

4. 테이블 이름은 "참석의사 확정 테이블"로 변경했습니다. 

5. 서로의 PK와 FK를 가질 수 있다고 생각했었는데 이부분에 대해서는 아직 지식이 부족한 것 같습니다. 정규화 부분은 따로 공부하겠습니다.

6. 커플 일정관리의 레코드 하나는 하나의 고객이며 그 고객은 신랑 1명, 신부 1명으로 이루어져 있습니다. 신랑 1명, 신부 1명을 1개의 레코드로 가지는 신랑신부 관리테이블을 하나의 테이블로 병합하여 새로 정의했습니다. 추가로, 커플 일정관리와 신랑신부 관리테이블은 1:1 관계라고 생각하여 1:n에서 1:1로 관계 재정의 했습니다.

2023-08-07 12:09 UTC, kakasoo approved these changes
일단 PR은 approve 상태로 바꾸겠습니다. 언제든 합칠 수 있도록 수정하는 것이니 이후에는 commit, push가 가능할 거에요.

2023-08-07 12:20 UTC, kakasoo commented
1
3번에 왜 couple_id가 있는지 설명해보세요. 관리자 계정이 커플 아이디를 가져야 하는 이유가 뭔가요? 커플마다 관리자가 생기고, 관리자마다 로그인이 가능한 구조인가요? 그러면 관리자는 커플인가요, 아니면 이 서비스를 만든 사람인가요? 어떤 기획을 생각 중인건지 모르겠습니다만, 10쌍의 커플이 있다면 10개의 관리자 계정이 필요한 건가요? 하나의 관리자가 여러 데이터를 조회할 수 있다면 관리자는 커플과 아무런 종속 관계 ( = FK ) 가 없어야 하는 게 맞습니다.
기획 의도와 용어를 명확히 통일하는 게 낫겠습니다. 관리자가 무얼 의미하는지 말씀해주세요.

2
tinyint는 칼럼의 타입을 말한 거였지, 칼럼 명을 말한 게 아니었습니다. tinyint는 좁은 범위의 int를 의미합니다. 저는 이걸로 신랑과 신부를 구분짓기를 원한 거지, PK로 하길 원한 게 아니었습니다. 어떤 테이블이든지 간에 PK 이름은 id로 통일하는 건 어떨까요? 그리고 `신랑/신부 구분에 대한 tinyint 칼럼을 하나 추가`하는 게 좋겠습니다.

3-1
신랑과 신부가 합쳐진 걸 편의 상 `User`라고 부를게요. 그러면 결혼일정은 2명의 유저가 결혼하는 거니깐 결혼일정에는 2개의 `user_id`가 필요하게 됩니다. 그러니 `first_user_id`, `second_user_id` 라는 칼럼이 필요하겠죠. 이름은 원하시는대로 정하시면 됩니다.

3-2
두 테이블이 합쳐졌기 때문에 신랑인가 신부인가를 구분짓는 tinyint가 있다고 한다면, 굳이 신부_전화번호_칼럼, 신부_계좌번호_칼럼, 신랑_전화번호_칼럼, 신랑_계좌번호_칼럼이 있을 필요가 없습니다. `그냥 전화번호와 계좌번호 칼럼으로 존재하게 해주세요.` 신랑, 신부 구분이 true일 때와 false일 때 전화번호와 계좌번호를 해석해보면 됩니다.

2023-08-07 12:25 UTC, kakasoo commented
정규화는 1단계부터 4단계 ( 5단계까지 설명하는 경우도 있음 ) 까지 있는데, 일단 이렇게 이해하세요.
`일대 다 관계에서는 다수가 일(1)의 아이디를 가져야 한다.`
예를 들어, 한 사람이 여러 대의 자동차를 가질 수 있다면 자동차는 주인의 아이디를 가지고 있어야 합니다.
여타 커머스가 그렇듯이 한 사람이 여러 개의 장바구니를 가질 수 있다면 장바구니들은 그 한 사람의 아이디를 가져야 한다.
많은 쪽이 적은 쪽의 아이디를 가져야 합니다.
하나의 테이블을 하나의 엑셀 row라고 표현한다면, 이렇게 말고는 표현할 방법이 없어요.

2023-08-08 08:01 UTC, Chanmi-Gim commented
<img width="550" alt="스크린샷 2023-08-08 오후 4 48 33" src="https://github.com/Chanmi-Gim/Express/assets/117872640/469c0a82-9112-4e09-af73-265fa6f48e6f">


**API 설명**
>**관리자페이지 API 기능**
> 1. 관리자 로그인
> 2. 관리자페이지의 기능은 크게 2가지로 나뉜다. 
>   - 계약관리 기능 : 계약 테이블, 신랑/신부관리 테이블의 정보조회
>   - 웹페이지 관리기능 : 1)참석의사 확정테이블, 방명록 테이블의 정보조회 2) 결혼일 10일 전, 신랑신부에게 참석의사 확정 정보 발송

>**웹페이지 API 기능**
>  1. 웹페이지에 접속하면 기본 페이지는 웨딩갤러리로 연결된다.
>  2. 왼쪽의 네비게이션을 클릭하면 4개의 각 페이지로 연결된다. 구성은 총 4가지이다. ( 웨딩갤러리, 위치, 참석의사, 신랑신부 연락하기)
>  3-1. 웨딩갤러리 : 웨딩갤러리와 방명록 기능
>    - 웨딩갤러리:  웨딩사진을 S3에서 받아와서 표출한다. 
>    - 방명록 : 익명의 방명록. 사용자가 게스트 이름, 패스워드, 내용을 적어 데이터로 보내면 방명록 테이블에 레코드 저장되고 화면에 표출된다. 만약, 삭제하고 싶으면 게스트 이름과 패스워드를 알면 가능하다(복합 PK)
>  3-2. 위치
>  3-3. 참석의사 : 결혼식에 참석할 사용자는 게스트 이름, 신부/신랑측 체크, 참석인원을 적어 데이터로 보내면 참석의사 확정테이블에 저장된다. 만약, 삭제하고 싶으면 게스트이름과 패스워드를 알면 가능하다(복합 PK)
>  3-4. 신랑신부 연락하기 : 신랑테이블과 신부테이블로부터 신랑/신부의 연락처, 신랑/신부 계좌번호 및 신랑/신부 부모 계좌번호를 표출한다.


**답변**
1. 하나의 관리자가 로그인하면 모든 테이블을 조회할 수 있습니다. 말씀하신 것처럼 관리자는 단순조회만 하므로 결혼일정관리 테이블과의 관계선을 삭제했습니다.

2. 고민해보았는데 신랑/신부를 구분하여 이벤트 정보제공 등을 발송할 수 있으므로 한꺼번에 신랑과 신부를 관리했던 신랑/신부관리테이블을 신랑테이블 신부테이블로 나누었습니다. 


+  제가 생각했던 설계와 유사해지기 위해서는 API 기능을 말씀드려야할 것 같아 정리해서 올렸습니다!! API를 제공시, 테이블 구조가 이상한 부분이 있거나 수정해야할 것 같다고 생각드는 부분이 있으면 말씀해주시면 감사하겠습니다.

2023-08-08 08:31 UTC, kakasoo commented
테이블에 PK는 무조건 1개입니다. 그리고 password는 절대 PK가 될 수 없습니다.present_number는 뭘 의미하나요? 칼럼마다 comment를 달아주면 더 좋을 거 같습니다.

2023-08-08 08:40 UTC, kakasoo commented
저 DB 상에서 말씀하신 기능들이 다 가능한지 한 번 살펴보세요.

- 웨딩 갤러리로 어떻게 연결하죠?
- 링크는 어떻게 발급할 건가요?
- 웨딩 사진이 뭔지 어떻게 아나요?
- 방명록에 게스트 이름과 패스워드로 삭제 가능하다고 했는데 게스트 이름은 어디에 저장하고 있나요?
    - 참석 의사도 마찬가지입니다.

2023-08-08 10:49 UTC, Chanmi-Gim commented
<img width="476" alt="스크린샷 2023-08-08 오후 7 49 02" src="https://github.com/Chanmi-Gim/Express/assets/117872640/5f2a2645-ea52-407f-9a50-59410a71233a">

# **1. PK 변경**
id에서 name으로 변경했습니다. 그 이유는, 방명록은 익명이기 때문에 작성 등록시 name, password를 기입을 해야합니다. id를 추가로 생성하기보다는 입력받은 name과 password 복합키로 사용하여 효율성을 높이고 싶었습니다. 따라서, 속성(id->name) 변경했습니다!

# **2. command**
> **관리자로그인 테이블**
> * id : 관리자 ID **[PK]** 
> * password : 관리자 PASSWORD
>
>**계약관리 테이블**
>* id : 계약번호  **[PK]**
>* wedding_date : 결혼일시
>* weddinghall_date : 결혼식장 주소
>
>**신랑 관리 테이블**
>* id : 신랑 id  **[PK]**
>* name : 신랑 이름
>* contact_number : 신랑 연락처
>* account_number : 신랑 계좌번호
>* father_account_number : 신랑 아버지 계좌번호
>* mother_account_number : 신랑 어머니 계좌번호
>* contract_id : 계약번호 **[FK]** 
>
>**신부 관리 테이블**
>* id : 신부 id  **[PK]**
>* name : 신부 이름
>* contact_number : 신부 연락처
>* account_number : 신부 계좌번호
>* father_account_number : 신부 아버지 계좌번호
>* mother_account_number : 신부 어머니 계좌번호
>* contract_id : 계약번호 **[FK]** 
>
>**참석의사 확정테이블**
>* name, password : 참석자 이름, 참석자 비밀번호  **[PK]**
>* bridal_side : 신부측/신랑측
>* present_number : 참석인원
>* contract_id : 계약번호 **[FK]** 
>
>**방명록 테이블**
>* name, password : 참석자 이름, 참석자 비밀번호  **[PK]**
>* content : 방명록 내용
>* contract_id : 계약번호 **[FK]** 
>
>**갤러리 테이블**
>* id : 사진 id  **[PK]**
>* title : 사진 제목
>* image_url : 사진 url 링크
>* image_size : 사진 size (계약시, 사진 크기 제한 확인을 위함)
>* constract_id : 계약번호 **[FK]**

# **3. API 설명**
>**관리자페이지 API 기능**
> 1. 관리자 로그인
> 2. 관리자페이지의 기능은 크게 2가지로 나뉜다. 
>   - 계약관리 기능 : 계약 테이블, 신랑/신부관리 테이블의 정보조회
>   - 웹페이지 관리기능 : 1)참석의사 확정테이블, 방명록 테이블의 정보조회 2) 결혼일 10일 전, 신랑신부에게 참석의사 확정 정보 발송

>**웹페이지 API 기능**
>  1. 웹페이지에 접속하면 기본 페이지는 웨딩갤러리로 연결된다.
>  2. 왼쪽의 네비게이션을 클릭하면 4개의 각 페이지로 연결된다. 구성은 총 4가지이다. ( 웨딩갤러리, 위치, 참석의사, 신랑신부 연락하기)
>  3-1. 웨딩갤러리 : 웨딩갤러리와 방명록 기능
>    - 웨딩갤러리:  웨딩사진url을 갤러리 테이블에서 받아와서 표출한다. 
>    - 방명록 : 익명의 방명록. 사용자가 게스트 이름, 패스워드, 내용을 적어 데이터로 보내면 방명록 테이블에 레코드 저장되고 화면에 표출된다. 만약, 삭제하고 싶으면 게스트 이름과 패스워드를 알면 가능하다(복합 PK)
>  3-2. 위치
>  3-3. 참석의사 : 결혼식에 참석할 사용자는 게스트 이름, 신부/신랑측 체크, 참석인원을 적어 데이터로 보내면 참석의사 확정테이블에 저장된다. 만약, 삭제하고 싶으면 게스트이름과 패스워드를 알면 가능하다(복합 PK)
>  3-4. 신랑신부 연락하기 : 신랑테이블과 신부테이블로부터 신랑/신부의 연락처, 신랑/신부 계좌번호 및 신랑/신부 부모 계좌번호를 표출한다.

#  **4. 변경사항**
웨딩 갤러리로 어떻게 연결하죠? _갤러리 테이블을 추가하여 image_url을 넣었습니다._
링크는 어떻게 발급할 건가요? _aws S3에 사진을 저장하여 발급한 url을 갤러리 테이블에 추가할 예정입니다._
웨딩 사진이 뭔지 어떻게 아나요? _갤러리 테이블을 생성했습니다._
방명록에 게스트 이름과 패스워드로 삭제 가능하다고 했는데 게스트 이름은 어디에 저장하고 있나요? _속성명 변경했습니다.(Id->name)_
참석 의사도 마찬가지입니다. _참석한 사람만 레코드를 작성할 수 있고, 참석한 사람이 신랑측/신부측인지 구분할 수 있도록 기획했습니다._

2023-08-08 11:25 UTC, kakasoo commented
모바일로 이동 중에 리뷰하니라 이미지가 안보이는데요~ 텍스트로 읽어봤을 땐 다 된 거 같네요. 다만 제가 말한 건 이미지도 이미지지만 결혼할 커플이 자기 청첩장 링크를 유저들에게 어떻게 뿌릴 것인지 말한 거 였어요. 이미지만 줄 수는 없잖아요.

청첩장 링크 제공을 위해 결혼 관리 테이블에 uuid를 저장할 varchar 칼럼을 하나 추가합시다. "어? GET couples/:id로 하면 되잖아요?" 라고 생각하실 수 있는데 그렇게 만들면 안됩니다! 왤까요?

나중에 답드립니다. 이 PR은 이제 OK!

2023-08-08 15:44 UTC, 8471919 commented
1. 관리자 테이블은 관리자가 서비스에 로그인 할 때 쓰이는 걸로 보이는데, 속성 중 id라는 칼럼은 그저 관리자의 고유 index번호를 의미하는 것이지 Identifier(아이디)를 의미하는 것이 아닙니다! 일부러 저렇게 테이블을 작성하셨을 수도 있을 것 같아서 조심스럽게 말해봅니다! 만약에 아니라면 관리자의 email이나 Identifier를 칼럼으로 받아야 할 거에요! ex) id(PK), email(혹은 username), password -> 이렇게 세 칼럼이 필요할 것으로 보입니다!
2. 방명록, 참석의사 테이블에도 password가 있는데, email 혹은 username 칼럼의 추가가 필요해 보입니다.(혹은 unique한 nickname칼럼) 그냥 고유 식별번호로 로그인하게 할 생각이라면 굳이 필요는 없어보이구요!(name과 password만으로 방명록을 지우거나, 참석의사를 확인할 수 없는 상황이 발생할 수 있습니다. 예를들어, 동명이인의 경우가 그렇습니다. // name과 password로 할 수는 있겠지만, 일치하는 이름의 유저를 한번에 뽑아서 비밀번호를 일일이 비교하는건 효율적이지 않을 것 같습니다.)
3. 그리고 신랑, 신부가 청첩장을 직접 관리할 수 있게 하려면... 신랑 신부측에도 로그인(혹은 인증)을 위한 칼럼인 email(혹은 username), password 칼럼이 필요하지 않을까요? -> 이건 개인 의견입니다! 넘어가셔도 됩니다.

일단 당장 보이는 것들은 이것들 입니다! 한 번 천천히 생각해보세요!

2023-08-09 06:10 UTC, merged